name: Nest Server
on:
  push:
    branches: [main]

jobs:
  create_env:
    runs-on: ubuntu-22.04
    steps:
      - name: Create .env
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /home/chat-server
            docker compose down
            if [ ! -f .env ]; then
              touch .env
              echo "PORT=${{ secrets.PORT }}" >> .env
              echo "NATS_URL=${{ secrets.NATS_URL }}" >> .env
              echo "NAME=${{ secrets.NAME }}" >> .env
              echo "PASS=${{ secrets.PASS }}" >> .env
              echo "DATABASE=${{ secrets.DATABASE }}" >> .env
              echo "SECRET=${{ secrets.SECRET }}" >> .env
              echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
              echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env
              cat .env
            fi
  deploy:
    needs: create_env
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            set -e
            cd /home/chat-server
            git pull origin main
            docker compose up -d